### ISSUE TITLE
Glyph appears off-screen on iPads in Landscape on iOS 9.0.2 

### ISSUE THREAD

**Issue by ReddestDream** [evilgoldfish/LockGlyph#6] opened 2015-10-17 19:39 UTC
The LockGyph appears off-screen on iPads in Landscape on iOS 9.0.2.

Adjusting Landscape Y to 700 can fix this, but the glyph is still not centered in the middle of the screen.

Attached please find a picture of the problem. Thanks! ^_^

![iqicnsy](https://cloud.githubusercontent.com/assets/4013634/10560846/3a4e1db4-74e5-11e5-8381-e65f5e918456.jpg)

**Comment by emeoleb** [comment] 2016-07-28 23:00
There is the same problem under iOS 9.3.3 with iPad Air 2.
It's a shame because this tweak is really great !

**Comment by evilgoldfish** [comment] 2016-07-29 06:57
i can reproduce this issue. simple fix as well - just need to use the same position for the glyph in portrait and landscape.

**Comment by ReddestDream** [comment] 2016-07-29 07:10
Thanks! I have an iPad Pro 12.9" (iOS 9.3.3) now and can help test on it! ^_^

**Comment by evilgoldfish** [comment] 2016-07-30 00:04
Fixed in commit 4e30f1a.

**Comment by ReddestDream** [comment] 2016-08-02 04:30
Unfortunately, it seems this issue is still not fixed on my iPad Pro. :/

**Comment by evilgoldfish** [comment] 2016-08-06 11:38
bug is still present on 9.3.3, latest commit has _not_ fixed the issue.

**Comment by emeoleb** [comment] 2016-08-08 22:32
It's OK for me on iPad Air 2 with the latest version (1.1.13-2  2016/08/08) and without ajusting Landscape.
Thanks !

**Comment by ReddestDream** [comment] 2016-08-08 22:34
@emeoleb Did you test in both Portrait and Landscape view on the lockscreen?

**Comment by emeoleb** [comment] 2016-08-08 22:38
@ReddestDream Yes, in both Portrait and Landscape.
The glyph appears in the bottom middle (centered).

**Comment by emeoleb** [comment] 2016-08-08 22:41
![image](https://cloud.githubusercontent.com/assets/20713308/17498804/ddcf9454-5dc9-11e6-85e3-955afb489e47.png)
![image](https://cloud.githubusercontent.com/assets/20713308/17498805/dde89cc4-5dc9-11e6-81ec-90925fd52c00.png)

**Comment by ReddestDream** [comment] 2016-08-08 22:43
Hmm. Your right. Seems to be fixed. Wow. I'll keep testing to totally confirm, but yes, it seems fixed for me too . . .

**Comment by evilgoldfish** [comment] 2016-08-08 22:48
yes, apparently optimo published the wrong update, or i sent the wrong update. either way, the bug is 100% fixed, and i really should install a build from my Mac onto my iPad next time.

**Closed by evilgoldfish** 2016-08-08 22:48 UTC
Labels: bug
